# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from object_detection/DetectionResults.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import object_detection.msg

class DetectionResults(genpy.Message):
  _md5sum = "c90c5dbacc052c188fd5956bea4e6f91"
  _type = "object_detection/DetectionResults"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """DetectionResult[] results
================================================================================
MSG: object_detection/DetectionResult
string out_class
float32 out_score
uint32 upper_left
uint32 upper_right
uint32 lower_left
uint32 lower_right"""
  __slots__ = ['results']
  _slot_types = ['object_detection/DetectionResult[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       results

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DetectionResults, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.results is None:
        self.results = []
    else:
      self.results = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.results)
      buff.write(_struct_I.pack(length))
      for val1 in self.results:
        _x = val1.out_class
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_f4I().pack(_x.out_score, _x.upper_left, _x.upper_right, _x.lower_left, _x.lower_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.results is None:
        self.results = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.results = []
      for i in range(0, length):
        val1 = object_detection.msg.DetectionResult()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.out_class = str[start:end].decode('utf-8')
        else:
          val1.out_class = str[start:end]
        _x = val1
        start = end
        end += 20
        (_x.out_score, _x.upper_left, _x.upper_right, _x.lower_left, _x.lower_right,) = _get_struct_f4I().unpack(str[start:end])
        self.results.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.results)
      buff.write(_struct_I.pack(length))
      for val1 in self.results:
        _x = val1.out_class
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_f4I().pack(_x.out_score, _x.upper_left, _x.upper_right, _x.lower_left, _x.lower_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.results is None:
        self.results = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.results = []
      for i in range(0, length):
        val1 = object_detection.msg.DetectionResult()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.out_class = str[start:end].decode('utf-8')
        else:
          val1.out_class = str[start:end]
        _x = val1
        start = end
        end += 20
        (_x.out_score, _x.upper_left, _x.upper_right, _x.lower_left, _x.lower_right,) = _get_struct_f4I().unpack(str[start:end])
        self.results.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f4I = None
def _get_struct_f4I():
    global _struct_f4I
    if _struct_f4I is None:
        _struct_f4I = struct.Struct("<f4I")
    return _struct_f4I
