# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from object_detection/DetectionResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DetectionResult(genpy.Message):
  _md5sum = "5fb792480f070cbc69af8da53d614697"
  _type = "object_detection/DetectionResult"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string out_class
float32 out_score
uint32 upper_left
uint32 upper_right
uint32 lower_left
uint32 lower_right"""
  __slots__ = ['out_class','out_score','upper_left','upper_right','lower_left','lower_right']
  _slot_types = ['string','float32','uint32','uint32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       out_class,out_score,upper_left,upper_right,lower_left,lower_right

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DetectionResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.out_class is None:
        self.out_class = ''
      if self.out_score is None:
        self.out_score = 0.
      if self.upper_left is None:
        self.upper_left = 0
      if self.upper_right is None:
        self.upper_right = 0
      if self.lower_left is None:
        self.lower_left = 0
      if self.lower_right is None:
        self.lower_right = 0
    else:
      self.out_class = ''
      self.out_score = 0.
      self.upper_left = 0
      self.upper_right = 0
      self.lower_left = 0
      self.lower_right = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.out_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_f4I().pack(_x.out_score, _x.upper_left, _x.upper_right, _x.lower_left, _x.lower_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.out_class = str[start:end].decode('utf-8')
      else:
        self.out_class = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.out_score, _x.upper_left, _x.upper_right, _x.lower_left, _x.lower_right,) = _get_struct_f4I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.out_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_f4I().pack(_x.out_score, _x.upper_left, _x.upper_right, _x.lower_left, _x.lower_right))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.out_class = str[start:end].decode('utf-8')
      else:
        self.out_class = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.out_score, _x.upper_left, _x.upper_right, _x.lower_left, _x.lower_right,) = _get_struct_f4I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f4I = None
def _get_struct_f4I():
    global _struct_f4I
    if _struct_f4I is None:
        _struct_f4I = struct.Struct("<f4I")
    return _struct_f4I
