#!/usr/bin/python
"""
couldn't find a better name for this script
Basically running the whole SD software on
data collected at Deerfield. (The geofenced area)
that the vehicle is operating
"""

import numpy as np
import pandas as pd
import cv2
import rospy
from sensor_msgs.msg import Image
from std_msgs.msg import Float32
from cv_bridge import CvBridge, CvBridgeError


class DataSimulator():

    def __init__(self):

        rospy.init_node('data_simulator')
