// Generated by gencpp from file object_detection/DetectionResults.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_DETECTIONRESULTS_H
#define OBJECT_DETECTION_MESSAGE_DETECTIONRESULTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <object_detection/DetectionResult.h>

namespace object_detection
{
template <class ContainerAllocator>
struct DetectionResults_
{
  typedef DetectionResults_<ContainerAllocator> Type;

  DetectionResults_()
    : results()  {
    }
  DetectionResults_(const ContainerAllocator& _alloc)
    : results(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::object_detection::DetectionResult_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_detection::DetectionResult_<ContainerAllocator> >::other >  _results_type;
  _results_type results;





  typedef boost::shared_ptr< ::object_detection::DetectionResults_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection::DetectionResults_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionResults_

typedef ::object_detection::DetectionResults_<std::allocator<void> > DetectionResults;

typedef boost::shared_ptr< ::object_detection::DetectionResults > DetectionResultsPtr;
typedef boost::shared_ptr< ::object_detection::DetectionResults const> DetectionResultsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection::DetectionResults_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection::DetectionResults_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'object_detection': ['/home/neil/Workspace/self-driving-golf-cart/ros/src/detection/object_detection/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::DetectionResults_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::DetectionResults_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::DetectionResults_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::DetectionResults_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::DetectionResults_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::DetectionResults_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection::DetectionResults_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9a646c35e7a13cc2d94d4de60869423";
  }

  static const char* value(const ::object_detection::DetectionResults_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9a646c35e7a13ccULL;
  static const uint64_t static_value2 = 0x2d94d4de60869423ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection::DetectionResults_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection/DetectionResults";
  }

  static const char* value(const ::object_detection::DetectionResults_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection::DetectionResults_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DetectionResult[] results\n\
================================================================================\n\
MSG: object_detection/DetectionResult\n\
uint32 out_class\n\
float32 out_score\n\
float32[] location\n\
";
  }

  static const char* value(const ::object_detection::DetectionResults_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection::DetectionResults_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.results);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionResults_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection::DetectionResults_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection::DetectionResults_<ContainerAllocator>& v)
  {
    s << indent << "results[]" << std::endl;
    for (size_t i = 0; i < v.results.size(); ++i)
    {
      s << indent << "  results[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_detection::DetectionResult_<ContainerAllocator> >::stream(s, indent + "    ", v.results[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_DETECTIONRESULTS_H
