// Generated by gencpp from file object_detection/DetectionResult.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_MESSAGE_DETECTIONRESULT_H
#define OBJECT_DETECTION_MESSAGE_DETECTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detection
{
template <class ContainerAllocator>
struct DetectionResult_
{
  typedef DetectionResult_<ContainerAllocator> Type;

  DetectionResult_()
    : out_class(0)
    , out_score(0.0)
    , location()  {
    }
  DetectionResult_(const ContainerAllocator& _alloc)
    : out_class(0)
    , out_score(0.0)
    , location(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _out_class_type;
  _out_class_type out_class;

   typedef float _out_score_type;
  _out_score_type out_score;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::object_detection::DetectionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection::DetectionResult_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionResult_

typedef ::object_detection::DetectionResult_<std::allocator<void> > DetectionResult;

typedef boost::shared_ptr< ::object_detection::DetectionResult > DetectionResultPtr;
typedef boost::shared_ptr< ::object_detection::DetectionResult const> DetectionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection::DetectionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection::DetectionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'object_detection': ['/home/neil/Workspace/self-driving-golf-cart/ros/src/detection/object_detection/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::DetectionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection::DetectionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::DetectionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection::DetectionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::DetectionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection::DetectionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection::DetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b7fae78ce58faba54a3eab2d7ca9e3c";
  }

  static const char* value(const ::object_detection::DetectionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b7fae78ce58fabaULL;
  static const uint64_t static_value2 = 0x54a3eab2d7ca9e3cULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection::DetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection/DetectionResult";
  }

  static const char* value(const ::object_detection::DetectionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection::DetectionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 out_class\n\
float32 out_score\n\
float32[] location\n\
";
  }

  static const char* value(const ::object_detection::DetectionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection::DetectionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.out_class);
      stream.next(m.out_score);
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection::DetectionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection::DetectionResult_<ContainerAllocator>& v)
  {
    s << indent << "out_class: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.out_class);
    s << indent << "out_score: ";
    Printer<float>::stream(s, indent + "  ", v.out_score);
    s << indent << "location[]" << std::endl;
    for (size_t i = 0; i < v.location.size(); ++i)
    {
      s << indent << "  location[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.location[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_MESSAGE_DETECTIONRESULT_H
