#!/usr/bin/env python
# Software License Agreement (BSD License)
#
# Copyright (C) 2012, Jack O'Quin
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of the author nor of other contributors may be
#    used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Revision $Id$

"""
Provide geographic information maps from Open Street Map on request.

This is just a toy node, useful for testing.
"""

from __future__ import print_function

PKG_NAME = 'osm_cartography'
import roslib; roslib.load_manifest(PKG_NAME)
import rospy

from geographic_msgs.srv import GetGeographicMap
from geographic_msgs.srv import GetGeographicMapResponse

from osm_cartography import xml_map

class ServerNode:
    
    def __init__(self):
        rospy.init_node('osm_server')
        self.srv = rospy.Service('get_geographic_map', GetGeographicMap,
                                 self.map_server)
        self.resp = None

    def map_server(self, req):
        """ GetGeographicMap service callback.

        :param req: Request.
        :returns: Response.
        """
        url = str(req.url)
        self.url = url
        rospy.loginfo('[get_geographic_map] ' + url)

        # if empty URL, return existing map
        if url == '' and self.resp is not None: 
            return self.resp

        self.resp = GetGeographicMapResponse()
        try:
            self.resp.map = xml_map.get_osm(url, req.bounds)
        except (IOError, ValueError) as e:
            rospy.logerr(str(e))
            self.resp.success = False
            self.resp.status = str(e)
        else:
            self.resp.success = True
            self.resp.status = url
            self.resp.map.header.stamp = rospy.Time.now()
            self.resp.map.header.frame_id = '/map'
        return self.resp

    def run(self):
        rospy.spin()

if __name__ == '__main__':
    server = ServerNode()
    try:
        server.run()
    except rospy.ROSInterruptException: pass
